services:
  - type: web
    name: nucliadb
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: NUCLIADB_HOST
        value: 0.0.0.0
      - key: NUCLIADB_PORT
        value: 8080
      - key: NUCLIADB_HEALTH_ENDPOINT
        value: true
      - key: NUCLIADB_DEBUG
        value: false
