services:
  - type: web
    name: nucliadb2
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NUCLIADB_HOST
        value: 0.0.0.0
      - key: NUCLIADB_PORT
        value: 8080
    plan: free
